version: '3.1'

services:
  web:
    restart: always
    image: chandramichael16/api-project-test
    ports:
      - 8005:8005
    # links:
    #   - mysql
  
  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /mysql:/var/lib/mysql
    
